# Generated by Django 2.1.7 on 2019-02-21 15:25

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='network_file',
            field=models.FileField(blank=True, storage=home.models.OverwriteStorage(), upload_to='network_files', verbose_name='Network File'),
        ),
    ]
